stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
      - src/data_ingestion.py
      - data/raw/dataset.csv
    outs:
      - data/processed/cleaned_data.csv

  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/processed/cleaned_data.csv
    outs:
      - models/model.pkl